#!/bin/sh
echo "Starting Application Base On Config for $1"
open -a Terminal.app ./_buildScripts/startPrettier.sh
open -a Terminal.app ./_buildScripts/startTestWatch.sh
open -a Terminal.app ./_buildScripts/startWebpackDevServer$1.sh

# open -a Terminal.app startWebpackDevServer --args $1

#cd "${BASH_SOURCE%/*}" && echo "----- NEWBEG" && echo $1 && npm run start


#echo "${SOURCE}/startWebpackDevServer $1" > /tmp/tmp.sh ; chmod +x /tmp/tmp.sh ; open -a Terminal /tmp/tmp.sh ; rm /tmp/tmp.sh
#open -a Terminal.app startWebpackDevServer --args $1
# open -a Terminal.app startWebpackDevServer --args $1
# open -a Terminal.app startPrettier
# open -a Terminal.app startTestWatch

# ./startWebpackDevServer $1 &
# ./startPrettier &
# wait

# open -a Terminal.app startPrettier
# open -a Terminal.app startTestWatch
#open -a Terminal.app npm start:$1
# if [ $1 = "local"]; then
#   open -a Terminal.app startWebpackDevServer
# else if [$1 = "localProxy"]; then
#   open -a Terminal.app startWebpackDevServer:$1
# else if [$1 = "localBEServices"]; then
#   open -a Terminal.app startWebpackDevServer:localBEServices
# else if [$1 = "liveDevEnv"]; then
#   open -a Terminal.app startWebpackDevServer:liveDevEnv
# else
#   open -a Terminal.app startWebpackDevServer
# fi
